#!/usr/bin/env tsx
/**
 * Hermes Chat theme CSS generator
 * -------------------------------
 * This script renders the deterministic CSS variable payload exposed by
 * `packages/const/src/theme.ts` to a static asset so marketing pages, in-app
 * surfaces, and documentation previews can hydrate the latest palette without
 * relying on developers to copy/paste values manually. The CLI intentionally
 * remains idempotent—running it multiple times writes identical content which
 * keeps git diffs and cache busting workflows predictable.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

import { buildHermesCssVariables } from '../../packages/const/src/theme';

const OUTPUT_PATH = process.env.HERMES_THEME_CSS_PATH ?? 'public/assets/hermes-chat/theme.css';

async function main(): Promise<void> {
  const absolutePath = resolve(process.cwd(), OUTPUT_PATH);
  const css = `/* Auto-generated by scripts/theme/generateCss.ts – do not edit manually. */\n${buildHermesCssVariables('all')}\n`;

  await mkdir(dirname(absolutePath), { recursive: true });
  await writeFile(absolutePath, css, 'utf8');

  // eslint-disable-next-line no-console -- CLI utility for operators/CI logs.
  console.log(`wrote Hermes theme CSS to ${absolutePath}`);
}

void main();
